### ISSUE TITLE
List block not translated

### ISSUE THREAD

**Issue by sfederici** [djsrv/snapinator#3]
The block "item # of _ in _" of the Variables category in project https://scratch.mit.edu/projects/322798348/editor/ ("cover" sprite) is not translated.

**Comment by djsrv** [comment]
I'm working on implementing unsupported blocks like these as custom blocks. I'm a bit busy right now, but I'll try to finish this up as soon as possible.

**Comment by sfederici** [comment]
Let me know if I can help with this.

**Comment by djsrv** [comment]
Implementations of missing blocks would be helpful!

**Comment by sfederici** [comment]
Good. Can you give me a few start up instructions on the relevant script/part of scripts where the missing blocks must be added?
I may also need also quick instructions on how to run locally the full tool. If this is not asking too much.

**Comment by djsrv** [comment]
I haven't implemented the code to handle this yet, but it will be relatively simple once I have Snap! implementations of the blocks. It would only require some tweaks to the unsupported block code at https://github.com/djsrv/snapinator/blob/3aab1d45ecd10d143488229420b85b246fd41755/src/objects/Block.tsx#L624-L628 and https://github.com/djsrv/snapinator/blob/3aab1d45ecd10d143488229420b85b246fd41755/src/Project.tsx#L169-L191 to insert custom block definitions instead of creating empty 'UNSUPPORTED' definitions.

Since the TypeScript changes would be so simple, the main area I need help is writing Snap! code for the missing blocks.

If you would like to work on the TypeScript, though:
1. [Install NPM](https://www.npmjs.com/get-npm) if you don't have it
2. Clone the repository and `cd` to its directory
3. Run `npm install` to install the dependencies
4. Make whatever changes you want - [VSCode](https://code.visualstudio.com/) has the best support for editing TypeScript
5. Run `npm run build`
6. [Set up a local testing server](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server)
7. Open `index.html` in your browser to run Snapinator

**Comment by djsrv** [comment]
Fixed by #7 :)
