### ISSUE TITLE
Wrong capitalization in message name

### ISSUE THREAD

**Issue by sfederici** [djsrv/snapinator#4]
For example, when translating project 
https://scratch.mit.edu/projects/395795340
the message "spiegazione" in sprite "Tasto Spiegazione" is translated "SPIEGAZIONE". This doesn't allow Snap to match the two messages.

**Comment by sfederici** [comment]
I thought I had found the same bag in project https://scratch.mit.edu/projects/404783934 where message "spiegazione - esempio 1" in sprite "francesca" shows up as "Spiegazione - esempio 1" when opened in Snap. But I realized that the message "Spiegazione - esempio 1" is not present in the snapinator output xml file. So it is a problem of Snap that for some reason capitalizes the message in the wrong way when opening the project.

**Comment by djsrv** [comment]
I was able to reproduce this issue with https://scratch.mit.edu/projects/361979328/ and it should be fixed by 96b9cd9fb98b55c6d39f767a2e917f693c1c193a

It seems Scratch sometimes stores message names with incorrect capitalization, and the correct name needs to be looked up from the message dictionary.

**Comment by sfederici** [comment]
Thanks a lot Dylan
